version: '3.8'
services:
  ecomm-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-v:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: springuser
      MYSQL_PASSWORD: MySQL-P
      MYSQL_DATABASE: jokr_db
    security_opt:
      - seccomp:unconfined
    networks:
      - ecomm-network
  ecomm-main:
    image: pacodevs/jokr:latest
    depends_on:
      - ecomm-mysql
    ports:
      - 8080:8080
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "wget -qO-
          https://raw.githubusercontent.com/eficode/wait-for/v2.2.0/wait-for |
          sh -s -- ecomm-mysql:3306 -- java -jar /work/target/app.jar"
      ]
    environment:
      DATABASE_HOST: ecomm-mysql
      DATABASE_USER: springuser
      DATABASE_PASSWORD: MySQL-P
      DATABASE_NAME: jokr_db
      DATABASE_PORT: 3306
    networks:
      - ecomm-network
  ecomm-front:
    build:
      context: .
    depends_on:
      - ecomm-main
    ports:
      - 80:3000
    networks:
      - ecomm-network
networks:
  ecomm-network: null
volumes:
  mysql-v:
    external: false
